name: ROS 2 CI

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - jazzy
        include:
          # Humble Ubuntu 22.04 (Jammy)
          - ros_distribution: humble
            docker_image: osrf/ros:humble-desktop
          # Jazzy Ubuntu 24.04 (Noble)
          - ros_distribution: jazzy
            docker_image: osrf/ros:jazzy-desktop

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: rplidar_ros2_driver
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-name: coverage-gcc
